import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/app/**/*.{ts,tsx}',
    './src/components/**/*.{ts,tsx}',
    './src/features/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface':                   '#f7f9fb',
        'surface-dim':               '#d8dadc',
        'surface-bright':            '#f7f9fb',
        'surface-container-lowest':  '#ffffff',
        'surface-container-low':     '#f2f4f6',
        'surface-container':         '#eceef0',
        'surface-container-high':    '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'on-surface':                '#191c1e',
        'on-surface-variant':        '#45464d',
        'outline':                   '#76777d',
        'outline-variant':           '#c6c6cd',
        'inverse-surface':           '#2d3133',
        'inverse-on-surface':        '#eff1f3',
        'primary':                   '#000000',
        'on-primary':                '#ffffff',
        'primary-container':         '#131b2e',
        'on-primary-container':      '#7c839b',
        'inverse-primary':           '#bec6e0',
        'primary-fixed':             '#dae2fd',
        'primary-fixed-dim':         '#bec6e0',
        'on-primary-fixed':          '#131b2e',
        'on-primary-fixed-variant':  '#3f465c',
        'secondary':                 '#775a19',
        'on-secondary':              '#ffffff',
        'secondary-container':       '#fed488',
        'on-secondary-container':    '#785a1a',
        'secondary-fixed':           '#ffdea5',
        'secondary-fixed-dim':       '#e9c176',
        'on-secondary-fixed':        '#261900',
        'on-secondary-fixed-variant':'#5d4201',
        'tertiary':                  '#000000',
        'on-tertiary':               '#ffffff',
        'tertiary-container':        '#0b1c30',
        'on-tertiary-container':     '#75859d',
        'error':                     '#ba1a1a',
        'on-error':                  '#ffffff',
        'error-container':           '#ffdad6',
        'on-error-container':        '#93000a',
        'background':                '#f7f9fb',
        'on-background':             '#191c1e',
        'surface-variant':           '#e0e3e5',
        'surface-tint':              '#565e74',
        'tertiary-fixed':            '#d3e4fe',
        'tertiary-fixed-dim':        '#b7c8e1',
        'on-tertiary-fixed':         '#0b1c30',
        'on-tertiary-fixed-variant': '#38485d',
      },
      borderRadius: {
        sm:      '0.125rem',
        DEFAULT: '0.25rem',
        md:      '0.375rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      spacing: {
        'unit':               '4px',
        'xs':                 '4px',
        'sm':                 '8px',
        'md':                 '16px',
        'lg':                 '24px',
        'xl':                 '48px',
        'container-max':      '1280px',
        'projection-margin':  '10%',
        'sidebar':            '256px',
      },
      fontFamily: {
        'display-projection': ['var(--font-playfair)', 'serif'],
        'headline':           ['var(--font-playfair)', 'serif'],
        'body':               ['var(--font-inter)', 'sans-serif'],
        'label':              ['var(--font-work-sans)', 'sans-serif'],
      },
      fontSize: {
        'display-projection': ['72px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg':        ['48px', { lineHeight: '56px', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md':        ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg':            ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md':            ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm':           ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      boxShadow: {
        'active': '0 12px 24px -10px rgba(19, 27, 46, 0.15)',
      },
      width: {
        'sidebar': '256px',
      },
    },
  },
  plugins: [],
}

export default config
